export const SET_FILTER_TYPE = 'SET_FILTER_TYPE';
export const SET_SORT_FIELD = 'SET_SORT_FIELD';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const SET_IS_BASKET = 'SET_IS_BASKET';
export const SET_PRODUCT_TO_BASKET = 'SET_PRODUCT_TO_BASKET';
export const SET_CLEAR_BASKET = 'SET_CLEAR_BASKET';
